

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5


  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9093:9093"
      - "9100:9100"
      - "9099:9099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://${kafka_outside_ip}:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9099
      KAFKA_JMX_HOSTNAME: kafka1
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent.jar=9100:/usr/app/jmx_exporter_config.yaml"
    volumes:
      - ./jmx/jmx_prometheus_javaagent.jar:/usr/app/jmx_prometheus_javaagent.jar
      - ./jmx/jmx_exporter_config.yaml:/usr/app/jmx_exporter_config.yaml
      - kafka1-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9095:9095"
      - "9101:9101" # JMX порт для брокера 2
      - "9809:9809"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9094,OUTSIDE://${kafka_outside_ip}:9095
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,OUTSIDE://0.0.0.0:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9809
      KAFKA_JMX_HOSTNAME: kafka2
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent.jar=9101:/usr/app/jmx_exporter_config.yaml"
    volumes:
      - ./jmx/jmx_prometheus_javaagent.jar:/usr/app/jmx_prometheus_javaagent.jar
      - ./jmx/jmx_exporter_config.yaml:/usr/app/jmx_exporter_config.yaml
      - kafka2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3
    ports:
      - "9097:9097"
      - "9102:9102" # JMX порт для брокера 3
      - "9709:9709"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9096,OUTSIDE://${kafka_outside_ip}:9097
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9096,OUTSIDE://0.0.0.0:9097
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9709
      KAFKA_JMX_HOSTNAME: kafka3
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent.jar=9102:/usr/app/jmx_exporter_config.yaml"
    volumes:
      - ./jmx/jmx_prometheus_javaagent.jar:/usr/app/jmx_prometheus_javaagent.jar
      - ./jmx/jmx_exporter_config.yaml:/usr/app/jmx_exporter_config.yaml
      - kafka3-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9094,kafka3:9096
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.2

  rabbitmq-node1:
    image: rabbitmq:3-management
    container_name: rabbitmq-node1
    hostname: rabbitmq-node1
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node1
    ports:
      - "15672:15672"  # Интерфейс управления
      - "5672:5672"    # Порт AMQP
    volumes:
      - rabbitmq-node1-data:/var/lib/rabbitmq
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.3
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq-node2:
    image: rabbitmq:3-management
    container_name: rabbitmq-node2
    hostname: rabbitmq-node2
    restart: unless-stopped
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node2
    depends_on:
      - rabbitmq-node1
    volumes:
      - rabbitmq-node2-data:/var/lib/rabbitmq
    command: >
      bash -c "
      rabbitmq-server -detached &&
      until rabbitmqctl await_startup; do sleep 2; done &&
      rabbitmqctl stop_app &&
      rabbitmqctl join_cluster rabbit@rabbitmq-node1 &&
      rabbitmqctl start_app &&
      exec rabbitmq-server
      "
    mem_limit: 512m
    cpus: 0.3
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq-node3:
    image: rabbitmq:3-management
    container_name: rabbitmq-node3
    hostname: rabbitmq-node3
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node3
    depends_on:
      - rabbitmq-node1
    volumes:
      - rabbitmq-node3-data:/var/lib/rabbitmq
    command: >
      bash -c "
      rabbitmq-server -detached &&
      until rabbitmqctl await_startup; do sleep 2; done &&
      rabbitmqctl stop_app &&
      rabbitmqctl join_cluster rabbit@rabbitmq-node1 &&
      rabbitmqctl start_app &&
      exec rabbitmq-server
      "
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.3
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: rabbitmq-exporter
    environment:
      - RABBIT_URL=http://rabbitmq-node1:15672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password
    ports:
      - "9419:9419"
    depends_on:
      - rabbitmq-node1
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.1

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devpassword
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    mem_limit: 256m
    cpus: 0.2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.2

volumes:
  rabbitmq-node1-data:
  rabbitmq-node2-data:
  rabbitmq-node3-data:
  kafka1-data:
  kafka2-data:
  kafka3-data:

networks:
  default:
    driver: bridge
