global:
  scrape_interval: 10s

scrape_configs:

  - job_name: kafka
    static_configs:
      - targets:
          - kafka1:9100
          - kafka2:9101
          - kafka3:9102

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq-exporter:9419

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090